services:
  api:
    build: ./api-image
    ports:
      - 127.0.0.1:80:5000
    depends_on:
      - message-db
  message-db:
    build: ./db-image
    environment:
      - MARIADB_ROOT_PASSWORD=guild
      - MARIADB_DATABASE=messageapi
    # unnecessary when actually running with the API, but nice for testing my SQL syntax
    ports:
      - 127.0.0.1:3306:3306
